services:
  - type: web
    name: explainer-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python explainer_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
